In [5]:
import cv2  # OpenCV
import urllib.request  # to open and read URL
import numpy as np

# OBJECT CLASSIFICATION PROGRAM FOR VIDEO IN IP ADDRESS

url = 'http://192.168.137.44/cam-lo.jpg'
winName = 'ESP32 CAMERA'
cv2.namedWindow(winName, cv2.WINDOW_AUTOSIZE)

classNames = []
classFile = 'coco.names'
with open(classFile, 'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath, configPath)
net.setInputSize(320, 320)
net.setInputScale(1.0 / 127.5)
net.setInputMean((127.5, 127.5, 127.5))
net.setInputSwapRB(True)

while True:
    imgResponse = urllib.request.urlopen(url)  # open the URL
    imgNp = np.array(bytearray(imgResponse.read()), dtype=np.uint8)
    img = cv2.imdecode(imgNp, -1)  # decode image

    img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)  # vertical

    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    if len(classIds) != 0:
        for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
            cv2.rectangle(img, box, color=(0, 255, 0), thickness=3)  # draw rectangle
            cv2.putText(img, classNames[classId - 1], (box[0] + 10, box[1] + 30),
                        cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)

    cv2.imshow(winName, img)  # show the image

    # wait for ESC to be pressed to end the program
    tecla = cv2.waitKey(5) & 0xFF
    if tecla == 27:
        break

cv2.destroyAllWindows()

[16] [[ 89 139 143 177]]
[16 16] [[ 84 124 153 195]
 [  3  10 235 303]]
[5] [[  2   6 237 297]]
() ()
() ()
() ()
() ()
() ()
() ()
() ()
() ()
() ()
() ()
[62] [[  2 222  64  98]]
() ()
() ()
() ()
() ()
() ()
() ()
() ()
[15 62] [[  7 270  67  49]
 [  7 270  67  49]]
[7] [[  5   9 227 310]]
() ()
() ()
() ()
() ()
() ()
() ()
() ()
() ()
[16 16] [[ 66 196  82 119]
 [ 10   7 229 302]]
() ()
() ()
[7] [[ 10  52 212 132]]
[44] [[ 14  50 221 126]]
() ()
[42] [[  0  54 230 153]]
[87 87] [[  5  16 220 234]
 [  0   7 200 155]]
[44] [[  0  41 219 127]]
() ()
[87  1] [[  4  20 221 244]
 [  2  32 222 223]]
() ()
[1] [[  2  26 216 240]]
[87] [[  3  22 218 233]]
[65] [[  0  18 222 242]]
[ 1 85] [[  0  54 202 178]
 [  1  27 210 214]]
[1] [[  1  37 205 199]]
[1] [[  0  52 203 183]]
[1] [[  0  27 210 219]]
() ()
[1] [[  0  83 185 153]]
[41  1] [[  1  44 202 194]
 [  0  58 192 177]]
() ()
[18  3] [[  2   4 126 111]
 [  1   5 126 113]]
() ()
() ()
[7] [[  6   7 222 313]]
[7] [[  2  11 238 309]]
() ()

KeyboardInterrupt: 

In [4]:
!pip install opencv-python